"""empty message

Revision ID: 550607affd8b
Revises: 
Create Date: 2020-10-21 20:45:17.320801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '550607affd8b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('paleta', sa.Integer(), nullable=False),
    sa.Column('cantidaddebotellas', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cantidaddebotellas'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('paleta'),
    sa.UniqueConstraint('sku')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('paleta', sa.Integer(), nullable=False),
    sa.Column('cantidaddebotellas', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cantidaddebotellas'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('paleta'),
    sa.UniqueConstraint('sku')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('product')
    # ### end Alembic commands ###
